language: php
php:
  - 7.2
before_script:
- cp .env.example .env
- composer self-update
- composer install --no-interaction
- php artisan key:generate

script:
- vendor/bin/phpunit

deploy:
skip_cleanup: true
github_token: "$GITHUB_TOKEN"
local_dir: pubic
on:
branch: master